### ISSUE TITLE
Leds issue | Release 1.5.0

### ISSUE THREAD

**Issue by HugoSilvaSantos** [CreatorDev/LetMeCreate#26]
Hi,

When compile this example -> https://docs.creatordev.io/ci40/guides/creating-applications/#method-3-gcc-on-ci40 ; I received the following error related with the leds:

```bash
root@myCi40:~/test# make
gcc main.c -lletmecreate_core -lletmecreate_click
/tmp/ccalClFo.o: In function `main':
main.c:(.text+0x20): undefined reference to `led_init'
main.c:(.text+0x2c): undefined reference to `led_init'
main.c:(.text+0x48): undefined reference to `led_switch_on'
main.c:(.text+0x54): undefined reference to `led_switch_on'
main.c:(.text+0x84): undefined reference to `led_switch_off'
main.c:(.text+0x90): undefined reference to `led_switch_off'
main.c:(.text+0xe0): undefined reference to `led_release'
main.c:(.text+0xec): undefined reference to `led_release'
collect2: error: ld returned 1 exit status
make: *** [Makefile:2: all] Error 1
```

The used version of LetMeCreate is 1.5.0 . This example works on release 1.3.0 .

Cheers,
Hugo

**Comment by francois-berder-imgtec** [comment]
It seems that shared libraries on the target do not have any symbols. During stripping, everything gets removed.

**Comment by nikhil-zinjurde-imgtec** [comment]
Issue raised in wrong repo?  Should have been added in LetMeCreate repo?

**Comment by francois-berder-imgtec** [comment]
@nikhil-zinjurde-imgtec  No, I think this issue could be left here.

It seems that when stripping the shared library, only the dyn sym table is left which means that pyletmecreate examples or letmecreate examples can still run correctly but it is not possible to compile on Ci40. Compiling on the Ci40 using static libraries works. I ping @HugoSilvaSantos to update the docs on docs.creatordev.io
